name: CountMe Update
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  update-countme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Get Count
        run: ./graph.sh
        working-directory: ${{ github.workspace }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Write Growth Charts to Repostiory
        uses: test-room-7/action-update-file@v2
        with:
            file-path: |
              growth_ublue.png
              growth_nonbazzite.png
              growth_bazzite.png
              growth_global.png
            commit-msg: Growth Chart Update ${{ steps.date.outputs.date }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
